name: Black

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  black:
    name: Black
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: snok/install-poetry@v1
    - run: |
        poetry install
        poetry run python -m black --check . 
    